### ISSUE TITLE
Design Doc Review: MVP List

### ISSUE THREAD

**Issue by RosemaryGonzaga** [Nikoobox/TreeCamp#2]
# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- Your four Hipcamp MVPs should be in this order: Spots, Bookings, Spots search, Reviews. Add "Spots" feature and remove "Top Destinations" (whitch should be a bonus feature).
    - Add specific bullet points for Spots. Users won't be able to add, edit, delete spots, so this feature should focus on presenting spots to users in different views (e.g., SpotIndex and SpotShow)
- Timing:
    - Hosting on Heroku should be done by EOD Monday 11/16, not 11/17. The last day for fullstacks is Friday 11/27, so give yourself 2-3 hours to work on the Production README that last day (11/27).
    - Give yourself 2-3 days for Spots (because it's your first feature after user auth and will likely take longer than you expect), and 2 days for Reviews
- User auth: include a bullet point for the demo login
- Bookings: 
    - I may be misreading this, but your first two bullet points sound like they are part of the "Spots" MVP, which involves setting up the Spots (treehouses) table and seeding the database with some spots in different locations. If that's correct, then move those bullet points to the "Spots" feature.
    - Describe the CRUD operations can be performed on bookings. A user can create and destroy bookings; can they also update them (update the dates, for example)?
- Reviews: Describe the CRUD operations that can be performed on reviews.

**Comment by Nikoobox** [comment]
Changes were made as per comments.

**Comment by Nikoobox** [comment]
Done
