### ISSUE TITLE
Design Doc Review: Database Schema & Sample Frontend State

### ISSUE THREAD

**Issue by RosemaryGonzaga** [Nikoobox/TreeCamp#3]
# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [ ] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- Make sure your table and column names are back-ticked (this will format them as code snippets) - see the bluebird schema example: https://github.com/appacademy/bluebird/wiki/schema
- `treehouses` should hold a lot more information, given that the a single listing's show page shows more info than just the name, body, location.
    - Add timestamps
    - Rename `body` to `description`: "body" is usually used to described the body of a text item, like the body of a post or comment or review
    - `location` should be broken out into multiple columns. 
        - Add a `country` column, b/c it looks like each treehouse listing is associated with a `country` and a `location`. For example, [this listing](https://www.hipcamp.com/connecticut/quarry-view-by-darlene-dean/quarry-view-by-darlene-and-dean) shows the country and location as "United States > Connecticut" on its show page. Similarly, [this listing](https://www.hipcamp.com/es/ana-c-s-land/the-storks-nest) shows the country and location as "Spain > Ana C.’s Land" 
        - You will also need to store coordinates so that you can implement the map feature. Add `longitude` and `latitude` columns with the appropriate data type
    - Add a `host_id` column, b/c every listing has a host and displays it on the listing page
- Go through a listing show page to figure out what additional information you may need to store in the database. For example, each listing describes the `campsite area`, `essentials`, `amenities`, `details` (check-in/check-out/cancellation info), `activities`. You don't need to include _all_ the information that's on a show page (for example: camping vehicle details, terrain, elevation), but I do recommend including enough if this information that your show page will look info-rich instead of lacking in detail. How do you plan to store information about the campsite area, essentials, etc? Would that be stored in separate tables or as columns in your `treehouses` table?
- Where will information about bookings be stored? You will need a `bookings` table.

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- After addressing my feedback on your schema, apply any changes made there to your sample state. For example, if you add or remove tables or columns, or if you change any names, do so here in the sample state as well. For example, you will need a `bookings` slice of state under `entities` to hold information fetched from the `bookings` table. (This info will be useful for displaying a list of all the current user's bookings)
- All the keys in your frontend state should be named in camelCase, following JavaScript naming conventions. Example: `author_id` should be `authorId`
- `treehouses` slice of state:
    Add a `reviewIds` key pointing to an array of ids for every review associated with the treehouse. You will need this info when displaying a list of all the reviews on any given treehouse show page. 
        - ActiveRecord makes it easy to populate these id arrays in your jBuilder views. Whenever you define a `has_many` association, ActiveRecord will automatically give you additional association methods, including one that generates an array of the associated ids. [For more info, see the documentation on `collection_singular_ids` in sections 4.3.1 and 4.3.1.6-7 in the Rails Association Basics guide.](https://guides.rubyonrails.org/association_basics.html)
- `errors --> session` slice of state should not have the same info as your `session` slice of state. The session errors should contain an array of error messages, such as `["Invalid credentials"]` or `["Username already exists", "Password must be 10 characters"]`

**Comment by Nikoobox** [comment]
Corrections were made. Please let me know if I missed anything important

**Comment by Nikoobox** [comment]
Done
