### ISSUE TITLE
MVP #1: User Auth

### ISSUE THREAD

**Issue by RosemaryGonzaga** [Nikoobox/TreeCamp#4]
Below is the checklist that I will use to review your first MVP, User Authentication. I will check the functionality tomorrow 11/18, and the styling on 11/19.

# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

# Comments (11/19)
* Right now I get a blank white page and an error in the browser console whenever I try to sign up, login, or use the demo login. I would prioritize fixing that so the core auth functionality works, and then I'll take another look.
* As for your earlier styling question: I would just apply a fixed width and height to each of the form inputs, and try to have the dimensions match those of Hipcamp. When I open the form on Hipcamp, the dimensions of the form and the inputs stay fixed even when I resize the window.

**Comment by Nikoobox** [comment]
Hello Rosemary,
Below is a list of remaining items:
1. Display 404 errors when redirected to random url.
2. clear errors.
3. login/sign up on ENTER click.
4. after login/signup, don't show login/signup, only logout.

**Comment by Nikoobox** [comment]
11/19: item #4 has been resolved

**Comment by Nikoobox** [comment]
Hi Rosemary, I just fixed majority of the issues under this item. There is a problem with making the site pixel perfect. Treecamp splash page was nearly identical, but, just recently, Hipcamp upgraded their website - added round corners, centered main h1 text etc. I don't think it would make sense to redesign Treecamp now. I'll try to find their old site screenshot. Thanks for the feedback

**Comment by Nikoobox** [comment]
All issues were fixed
